### ISSUE TITLE
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by bpruss** [jakubroztocil/httpie#567]
New to HTTPie, this works in curl but not in HTTPie.  I have not upgraded to python 3 as I am working on 
AWS Lambda and it only supports python 2.7. 

bpruss@Ubuntu-AWSD01:~/helloworld$ http --debug https://pdffjaur49.execute-api.us-east-1.amazonaws.com/dev/
HTTPie 1.0.0-dev
Requests 2.13.0
Pygments 2.2.0
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
/usr/bin/python
Linux 4.2.0-35-generic

<Environment {
    "colors": 8, 
    "config": {
        "__meta__": {
            "about": "u'HTTPie configuration file'", 
            "help": "u'https://httpie.org/docs#config'", 
            "httpie": "u'0.9.9'"
        }, 
        "default_options": "[]"
    }, 
    "config_dir": "/home/bpruss/.httpie", 
    "is_windows": false, 
    "stderr": "<open file '<stderr>', mode 'w' at 0x7f1140bb31e0>", 
    "stderr_isatty": true, 
    "stdin": "<open file '<stdin>', mode 'r' at 0x7f1140bb30c0>", 
    "stdin_encoding": "UTF-8", 
    "stdin_isatty": true, 
    "stdout": "<open file '<stdout>', mode 'w' at 0x7f1140bb3150>", 
    "stdout_encoding": "UTF-8", 
    "stdout_isatty": true
}>

>>> requests.request(**{
    "allow_redirects": false, 
    "auth": "None", 
    "cert": "None", 
    "data": {}, 
    "files": {}, 
    "headers": {
        "User-Agent": "HTTPie/1.0.0-dev"
    }, 
    "method": "get", 
    "params": {}, 
    "proxies": {}, 
    "stream": true, 
    "timeout": 30, 
    "url": "u'https://pdffjaur49.execute-api.us-east-1.amazonaws.com/dev/'", 
    "verify": true
})

http: error: SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure while doing GET request to URL: https://pdffjaur49.execute-api.us-east-1.amazonaws.com/dev/
Traceback (most recent call last):
  File "/usr/local/bin/http", line 11, in <module>
    load_entry_point('httpie==1.0.0.dev0', 'console_scripts', 'http')()
  File "/usr/local/lib/python2.7/dist-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 227, in main
    log_error=log_error,
  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 99, in program
    final_response = get_response(args, config_dir=env.config.directory)
  File "/usr/local/lib/python2.7/dist-packages/httpie/client.py", line 70, in get_response
    response = requests_session.request(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
bpruss@Ubuntu-AWSD01:~/helloworld$ curl https://pdffjaur49.execute-api.us-east-1.amazonaws.com/dev/
{"hello": "world Bernie"}bpruss@Ubuntu-AWSD01:~/helloworld$

**Comment by bpruss** [comment]
I kept reading the docs and came across the caveats for working with Python 2.7. 
I uninstalled httpie and re-installed with the latest stable version.  
Then: 
sudo -H pip install --upgrade requests[security]

Now it works.
